app/models.py
from . import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__='users'
    id = db.Column(db.Integer, primary_key=True)
    username = db. Column(db.String(255), unique=True, nullable=False)
    email = db. Column(db.String(255), unique=True, nullable=False)
    profile_pic_path = db.Column(db.String(255), nullable=False, default='default.jpg')
    password_hash = db.Column(db.String(255), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)
    bio = db.Column(db.Text)
    comments = db.relationship('Comment',backref='author',lazy='dynamic')


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)


    def __repr__(self):
        return f"User{self.username}"


class Post(db.Model):
    __tablename__='posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    content = db.Column(db.Text, nullable=False)
    date_posted = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    user_id =db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    comments = db.relationship('Comment',backref='post',lazy='dynamic')
    def __repr__(self):
        return f"User{self.title}"

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.Text(),nullable = False)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    post_id = db.Column(db.Integer,db.ForeignKey('posts.id'),nullable = False)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,post_id):
        comments = Comment.query.filter_by(post_id=post_id).all()

        return comments

    
    def __repr__(self):
        return f'comment:{self.comment}'

class Subscriber(db.Model):
    __tablename__='subscribers'

    id = db.Column(db.Integer,primary_key=True)
    email = db.Column(db.String(255),unique=True,index=True)

    def save_subscriber(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f"Subscriber {self.email}"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField
from wtforms.validators import InputRequired


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [InputRequired()])
    submit = SubmitField('Submit')

class PostForm(FlaskForm):
    title =StringField('Title', validators=[InputRequired()])
    content = TextAreaField('Content', validators=[InputRequired()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = TextAreaField('Leave a comment',validators=[InputRequired()])
    submit = SubmitField('Comment')
    

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail



bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()



def create_app(config_name):
    app = Flask(__name__)


# Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Configuring the UploadSet
    configure_uploads(app,photos)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort, flash
from ..models import User, Post, Comment, Subscriber
from . import main
from flask_login import login_required, current_user
from .. import db, photos
from .forms import UpdateProfile, PostForm, CommentForm
from ..requests import get_quotes
from ..email import mail_message


@main.route('/')
def home():
    quotes= get_quotes()
    posts= Post.query.order_by(Post.date_posted.desc()).all()
    title="My Learning post"
    return render_template('home.html', title=title, posts=posts, quote=quotes)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route('/post/new',methods= ['GET','POST'])
@login_required
def new_post():
    subscribers = Subscriber.query.all()
    postform=PostForm()
    if postform.validate_on_submit():
        post = Post(title=postform.title.data, content=postform.content.data, user_id=current_user._get_current_object().id)
        db.session.add(post)
        db.session.commit()
        for subscriber in subscribers:
            mail_message("New post created!","email/new_post",subscriber.email,post=post)
        return redirect(url_for('.home'))
        flash('Your post has been posted!', 'success')

    return render_template('create_post.html',postform =postform, title='New Post',legend='New Post')

@main.route('/comment/<int:post_id>', methods = ['POST','GET'])
@login_required
def comment(post_id):
    commentform = CommentForm()
    post = Post.query.get(post_id)
    comments = Comment.query.filter_by(post_id = post_id).all()
    if commentform.validate_on_submit():
        comment = commentform.comment.data 
        post_id = post_id
        user_id = current_user._get_current_object().id
        new_comment = Comment(comment = comment,user_id = user_id,post_id = post_id)
        new_comment.save_comment()
        return redirect(url_for('.comment', post_id = post_id))
    return render_template('comment.html', commentform =commentform, post = post, comments=comments)


@main.route('/post/<int:post_id>', methods = ['GET','POST'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', post = post, title=post.title)

@main.route('/post/<int:post_id>/update', methods = ['GET','POST'])
@login_required
def updatepost(post_id):
    post = Post.query.get(post_id)
    if post.author != current_user:
        abort(403)
    postform = PostForm()
    if postform.validate_on_submit():
        post.title = postform.title.data
        post.content = postform.content.data
        db.session.commit()

        flash('Your post has been updated!', 'success')
        return redirect(url_for('main.post',post_id = post.id)) 
    elif request.method == 'GET':
        post.title = postform.title.data
        post.content = postform.content.data

    return render_template('create_post.html', postform = postform, title='Update Post',legend='Update Post')

@main.route('/post/<int:post_id>/delete', methods = ['POST'])
@login_required
def deletepost(post_id):
    post = Post.query.get(post_id)
    if post.author != current_user:
        abort(403)
        db.session.delete(post)
        db.session.commit()
        flash('Your post has been deleted!', 'warning')
        return redirect(url_for('.home'))

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block navbar %}
    {% include 'nav.html' %}
{% endblock %}
{% block styles %}
    {{ super() }}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&family=Ubuntu:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
    <div class="container" >
        <div class="row">
            {% if comments %}
                <div class="col-md-7" >
                    <h3 class="text-center">All comments for the post</h3>
                    {% for comment in comments %}
                    <div class="card w-90 mb-3" >
                        <div class="card-body text-center">
                            <h6>{{comment.id}}.</h6>
                            <h5>{{comment.post.title}}</h5>
                            <p class="card-title text-center">"{{ comment.comment }}", says {{comment.author.username|title()}}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-md-5  commentform" >

                        {{wtf.quick_form(commentform)}}
                </div>
            </div>
            {%else%}
            <div class="card w-90 mb-3">
                <div class="card-body">
                <p class="card-title">This post has no comment.</p>
                </div>
            </div> 
            <div class="col-md-5">
                    {{wtf.quick_form(commentform)}}
                </div>
            {%endif%}
    </div>

{% endblock%}

app/templates/create_post.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">
    <h2 class="text-center">Post your blog here!</h2>
    {{wtf.quick_form(postform)}}
</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1 class=" text-danger text-center mt-50">OOOPS! We cannot find the page you are looking for. Check url</h1>
{% endblock %}

app/templates/home.html
{% extends 'base.html'%}
{% block content%}
<div class="container-fluid" id="quote">
    <h1>We keep you entertained with these awesome quotes</h1>
    <div class="quote px-5">
        <p class="card-text">"{{quote.quote}}"</p>
        <h3>Author: <span style="color: rgb(3, 3, 3)">{{quote.author}}</span> </h3>
    </div> 
</div>
<div class="container-fluid mb-20" id="posts">
    <h1 class="text-center mt-50 p-20"><strong>Myblog</strong></h1>
    <div class="row">
        {% for post in posts %}
            <div class="col-md-3 col-sm-4 d-flex justify-content-center">
                <div class="card">
        <img style="border-radius: 50px;" class="rounded-circle" width="100px" height="100px" class="card-img-top" src="{{url_for('static',filename= post.author.profile_pic_path)}}" alt="Card image cap">
                    <div class="card-body">
                    <h3><a style="color: rgb(23, 116, 116); font-weight: 700;" href="{{url_for('main.post',post_id = post.id)}}">{{post.title}}</a></h3>
                            <h4 class="card-title">Author: {{post.author.username|title()}}</h4>
                        </a> 
                        <p class="card-text">{{post.content | truncate(150)}}</p>
                        <h4><span> Date posted:</span>{{post.date_posted.strftime("%Y-%m-%d")}}</4>
                    </div>
                <p><a href="{{url_for('main.comment',post_id = post.id)}}" class="btn btn-info btn-sm text-center"> Comments</a></p>
                  </div>
            </div>
        {% endfor %}
    </div>
        <div class="footer bg-dark justify-content-center center">
            <p class="copyright">copyright &copy; 2022 Esther Anyona | Myblog</p>
        </div>
</div>
{% endblock %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <h2 class="navbar-brand mx-5 " href="{{url_for('main.home')}}" >Myblog</h2>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ">
          <a class="nav-link active mx-5" aria-current="page" href="{{url_for('main.home')}}">Home</a>
          <a class="nav-link active mx-5" aria-current="page" href="{{url_for('main.new_post')}}">New Post</a>
          
        </div>
  
        <div class="collapse navbar-collapse justify-content-end mx-5" id="navbarNavAltMarkup">
          <div class="navbar-nav ">
  
            {% if current_user.is_authenticated %}
            <img style="border-radius: 50px;" class="rounded-circle" width="80px" height="80px" src="{{url_for('static',filename=current_user.profile_pic_path)}}" alt="prof-pic" class="img-thumbnail">
            <a class="nav-link text-white" aria-current="page" href="{{url_for('main.profile',uname=current_user.username)}}"><strong> {{current_user.username}} </strong><span class="mx-lg-5"> Profile</span></a>
            <a class="nav-link text-white" aria-current="page" href="{{url_for('auth.logout')}}">Logout</a>
  
            {%else%}
            <a class="nav-link mx-lg-5 text-white" aria-current="page" href="{{url_for('auth.login')}}">Login</a>
            {% endif %}
          </div>
      </div>
    </div>
  </nav>

app/templates/post.html
{% extends 'base.html'%}
{% block content%}
<div class="container-fluid" id="posts">
    <div class="card p-5">
        <div class="row">
            <div class="col-md-3 d-flex justify-content-center">
            <div>
                <div class="card">

                <img style="border-radius: 50px;" class="rounded-circle" width="100px" height="100px"src="{{url_for('static',filename= post.author.profile_pic_path)}}" alt="">
                <h3 style="color: rgb(23, 116, 116); font-weight: 700;">{{post.title}}</h3>
                <p>{{post.content}}</p>
            {% if post.author==current_user %}
                    <a href="{{url_for('main.updatepost', post_id=post.id)}}" class="btn btn-primary btn-sm m-2">Update</a>
                        <button class="btn btn-danger btn-sm m-2" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                </div>
            {% endif%}
                <h5><span>Author: </span>{{post.author.username|title()}}</h5>
                <p><span> Date posted:</span>{{post.date_posted.strftime("%Y-%m-%d")}}</p>
            </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete post?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{url_for('main.deletepost', post_id=post.id)}}" method="POST">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
    <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
        </div>
        <div class="col-md-4">
            {% if user == current_user %}
            <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
                <input type="file"  name="photo" class="form-control" required>
                <input type="submit">
              </form>
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %} 
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}